### PR TITLE
Fix/ Display user email in top bar

### LINKED ISSUE #29: Display user email in top bar
Use backend route `/user/account/` to fetch user details which include email.

### PR DESCRIPTION
**Pull request by irubido**
- stores email to local storage and redux

Closes #29

### CODE REVIEW

File: src/containers/Register/UserSlice.ts [hunk 1]
```diff
@@ -38,6 +39,7 @@ const initialState: IUserState = {
     loginSuccessValue: false,
     loginErrorValue: null,
     token: loadValidToken(),
+    email: localStorage.getItem("email"),
```
Comment (morrigan) [inline src/containers/Register/UserSlice.ts]: No need for the email to be in the local storage. In case it gets changed, you need to keep track of it and there is really no point it keeping it in the local storage as it doesn't differ from other data really.

Comment (morrigan) [reply src/containers/Register/UserSlice.ts]: Oh, I see why you meant local storage.. We have on backend an endpoint that returns user data so you can fetch it always - `user/account`. This is much better approach as it can be more data in the user account (name, nationality etc.) that should be loaded.

File: src/containers/Register/UserSlice.ts [hunk 2]
```diff
@@ -126,3 +133,16 @@ export const submitUserLogin = (data: IUser): AppThunk => async (dispatch): Prom
...
 };
+
+export const getUserEmail = (): AppThunk => async (dispatch, getState): Promise<void> => {
+    try {
+        const token = getState().user.token;
+        const response = await fetchUserEmail(token);
+        if (response.data) {
+            dispatch(saveEmail(response.data.email));
+        }
+        console.log(response);
```
Comment (morrigan) [inline src/containers/Register/UserSlice.ts]: Remove console log and enable no-console rule in eslint pls :D
