### PR TITLE
Fix/ Handle empty data in charts

### LINKED ISSUE #48: Handle empty data in charts

### PR DESCRIPTION
**Pull request by irubido**
- using EmptyList with prop for padding, except for Uptime chart

Closes #48

### CODE REVIEW

File: src/containers/DiskSpace/DiskSpaceChart.tsx [hunk 1]
```diff
@@ -12,19 +12,22 @@ type DiskSpaceChartProps = {
 export class DiskSpaceChart extends ChartWrapper<DiskSpaceChartProps> {
     public render(): ReactElement {
         const {data, onMouseMove} = this.props;
+        console.log("data");
```
Comment (morrigan) [inline src/containers/DiskSpace/DiskSpaceChart.tsx]: remove console logs

File: src/components/EmptyList/EmptyList.tsx [hunk 2]
```diff
@@ -3,11 +3,12 @@ import Search from "@material-ui/icons/Search";
 
 interface IEmptyListProps {
     message: string;
+    padding: "diskSpace" | "miningRewards" | "nodeList";
```
Comment (morrigan) [inline src/components/EmptyList/EmptyList.tsx]: Why padding is dependent on the graph type? That should definitely be avoided...

**Comment by morrigan** [comment]
Screenshot 2020-03-16 at 23 52 08
